apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: jfstx4njf-python 
  janus-idp.io/tekton: jfstx4njf-python
  backstage.io/kubernetes-id: jfstx4njf-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: jfstx4njf-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml